### ISSUE TITLE
UAPhoneGap program does not run

### ISSUE THREAD

**Issue by jvence** [urbanairship/ios-phonegap-plugin#2]
I've downloaded the latest, followed instructions and tries to run the example (after modifying app key, secret key and using the appropriate provisioning profile). Firstly it seems that phonegap loads fine (used window.alert to test). 

After   window.plugins.pushNotification.register(successCallback, errorCallback, [{ alert:true, badge:true, sound:true }]); is called, none of the callback functions are evoked. Nothing appears in Xcode 4 log console other then:

2011-10-02 19:05:58.166 UAPhoneGap[15651:707] Device initialization: DeviceInfo = {"name":"Jean's iPad","uuid":"[hidden by me]","platform":"iPad","gap":"1.0.0","version":"4.3.5","connection":{"type":"wifi"}};
[Switching to process 12291 thread 0x0]

Not sure how to proceed.

**Comment by jvence** [comment]
Forgot to mention that this was running on Xcode 4 with the phonegap-1.0.0

**Comment by jrwpersonal** [comment]
I had the same problem.

It was caused by the fact that I actually had a phonegap-1.1.0 framework but the example from UA includes/assumes phone gap-1.0.0 (javascript). Make sure you grab phonegap-1.1.0 and replace the phonegap-1.0.0.js with the one from 1.1 and it will work.

**Comment by jvence** [comment]
Thanks  jrwpersonal. You saved me and in fact it works fine now.
